name: Dotfiles Automation

on:
  push:
  schedule:
    - cron:  '0 6 * * 1'

jobs:

  dotfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: run shellcheck
      run: |
        cd home
        shellcheck .bash*[^includes] -x
        shellcheck $(grep -lR "#\!/bin/bash" bin)
    - name: test python scripts
      run: |
        cd home/bin/marathon && python -m unittest marathon_test.py
    - name: Report Job Status
      if: always()
      run: |
        if [[ $status == "failure" ]]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"dotfiles: build has failed!"}' "${WEBHOOK_URL}"; fi
      env:
        status: ${{job.status}}
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
